version: '3.3'
services:
  nginx:
    restart: always
    build:
      context: ./.nginx
      dockerfile: C:\Users\Nagar\Desktop\node_web\Hunlu\.nginx\Dockerfile
    ports:
      - 80:80
    networks:
      - network
    depends_on:
      - api
      - web
  api:
    build:
      context: ./api
      dockerfile: C:\Users\Nagar\Desktop\node_web\Hunlu\api\Dockerfile
    restart: always
    networks:
      - network
    depends_on:
      - redis
    volumes:
      - './api:/usr/src/api'
    expose:
      - 2525
    ports:
      - '2525:2525'
    env_file: ./api/.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  web:
    stdin_open: true
    build:
      context: ./web
      dockerfile: C:\Users\Nagar\Desktop\node_web\Hunlu\web\Dockerfile
    restart: always
    networks:
      - network
    depends_on:
      - api
    volumes:
      - './web:/usr/src/web'
    expose:
      - 3000
    ports:
      - '3000:3000'
  redis:
    image: redis
    restart: unless-stopped
    networks:
      - network
networks:
  network:
    driver: bridge
